import './polyfills';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import '@fontsource-variable/manrope';
import '@fontsource-variable/geist-mono';
import '@solana/wallet-adapter-react-ui/styles.css';
import { Wallets } from './wallet';
import Root from './Root';
import './styles.css';
import './wallet-modal.css';
createRoot(document.getElementById('root')!).render(<StrictMode><Wallets><Root /></Wallets></StrictMode>);
